// Auto-generated by build/dashboard_assets.py.
// Edit dashboard.css / dashboard.js / dashboard_html_part_*.html,
// then re-run dashboard_assets.py. Do not edit by hand.
#pragma once
#include "AutoLink.h"

namespace autolink {
static const char DASHBOARD_HTML_PART_A[] = R"DASH(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
<title>AutoLink Monitor</title>
<style>)DASH";
static const char DASHBOARD_CSS[] = R"DASHCSS(
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f0f2f5;color:#111827;min-height:100vh}
/* Hide Ping-only controls (fill mode radio, pause/start) when the
   device is a Pong. Pong is receive-only, so these are meaningless
   affordances. The body[data-role="pong"] attribute is set by the
   /stats poll handler once we know the role. Default: show
   everything (until the first /stats response lands, the user
   doesn't yet know if they're looking at Ping or Pong). */
body[data-role="pong"] .ping-only{display:none}
header{background:#ffffff;padding:14px 18px;display:flex;align-items:center;justify-content:space-between;border-bottom:2px solid #d1d5db;position:sticky;top:0;z-index:10;box-shadow:0 2px 8px rgba(0,0,0,.08);gap:10px;flex-wrap:wrap}
h1{font-size:18px;font-weight:700;letter-spacing:.2px}
.sub{font-size:13px;color:#6b7280;margin-top:3px}
.pill{padding:6px 16px;border-radius:20px;font-size:13px;font-weight:700;letter-spacing:.5px;transition:background .3s,color .3s}
.ok{background:#d1fae5;color:#065f46}
.swp{background:#fee2e2;color:#991b1b}
.lck{background:#fef9c3;color:#92400e}
main{padding:14px;max-width:540px;margin:0 auto}
.alert{background:#fee2e2;border:1px solid #f87171;border-radius:10px;padding:10px 14px;color:#991b1b;font-size:14px;text-align:center;margin-bottom:12px;display:none}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:14px}
.card{background:#ffffff;border:1px solid #d1d5db;border-radius:12px;padding:14px;box-shadow:0 1px 3px rgba(0,0,0,.06)}
.lbl{font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.9px;margin-bottom:7px;font-weight:600}
.val{font-size:26px;font-weight:700;font-variant-numeric:tabular-nums;line-height:1.1}
.g{color:#059669}.b{color:#2563eb}.r{color:#dc2626}.a{color:#7c3aed}
.hint{font-size:11px;color:#6b7280;margin-top:3px;font-variant-numeric:tabular-nums}
.row{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:8px;flex-wrap:wrap}
.section-lbl{font-size:12px;font-weight:700;color:#374151;text-transform:uppercase;letter-spacing:.6px}
.btns{display:flex;gap:6px;flex-wrap:wrap;align-items:center}
.btn{font:600 12px -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;padding:7px 12px;border:1px solid #d1d5db;background:#fff;border-radius:8px;cursor:pointer;color:#374151;transition:background .15s;-webkit-tap-highlight-color:transparent;user-select:none}
.btn:hover{background:#f3f4f6}
.btn.on{background:#dbeafe;color:#1d4ed8;border-color:#93c5fd}
.btn.pause.on{background:#fef3c7;color:#92400e;border-color:#fcd34d}
.btn.rst{color:#dc2626;border-color:#fca5a5}
.btn.rst:hover{background:#fef2f2}
.btn.rbt{color:#7c2d12;border-color:#fdba74;background:#fff7ed}
.btn.rbt:hover{background:#ffedd5}
.lvl-group{display:inline-flex;border:1px solid #d1d5db;border-radius:8px;overflow:hidden;background:#f9fafb;flex-wrap:wrap}
.lvl-group label{display:flex;align-items:center;gap:4px;padding:6px 10px;font-size:12px;font-weight:600;color:#374151;cursor:pointer;-webkit-tap-highlight-color:transparent;border-right:1px solid #d1d5db;user-select:none}
.lvl-group label:last-child{border-right:none}
.lvl-group input[type=radio]{margin:0;accent-color:#2563eb}
.lvl-group label.on{background:#dbeafe;color:#1d4ed8}
.role-pill{background:#e0e7ff;color:#3730a3;padding:3px 10px;border-radius:12px;font-size:13px;font-weight:600;letter-spacing:.3px;margin-left:6px}
.role-pill.empty{display:none}
.log-wrap{position:relative}
.log{background:#1f2937;color:#e5e7eb;font:11px ui-monospace,Menlo,Consolas,monospace;border-radius:10px;padding:10px 12px;height:200px;overflow-y:auto;line-height:1.5;border:1px solid #d1d5db}
.log>div{white-space:pre-wrap;word-break:break-all}
.log .E{color:#fca5a5}.log .W{color:#fcd34d}.log .I{color:#93c5fd}.log .D{color:#9ca3af}.log .V{color:#c4b5fd}
.log-fill-bar{height:5px;border-radius:0 0 8px 8px;background:linear-gradient(to right,#22c55e var(--pct,0%),#e5e7eb var(--pct,0%));border:1px solid #d1d5db;border-top:none;transition:background 0.3s}
.log-overlay{display:none;position:fixed;inset:0;z-index:9999;background:#fff;flex-direction:column}
.log-overlay.open{display:flex}
.log-overlay .log{flex:1;height:auto;border-radius:0;border:none;border-bottom:1px solid #d1d5db}
.log-overlay .log-fill-bar{border-radius:0;border:none;border-top:1px solid #e5e7eb}
.log-overlay-hdr{display:flex;align-items:center;justify-content:space-between;padding:8px 14px;border-bottom:1px solid #d1d5db;background:#f9fafb}
.log-overlay-hdr>span{font-weight:600;font-size:14px}
.log-overlay-close{padding:6px 12px;border:1px solid #d1d5db;background:#fff;border-radius:8px;font:600 12px -apple-system,sans-serif;cursor:pointer}
.footer{text-align:center;font-size:11px;color:#6b7280;padding:12px 8px 24px}
.footer span{font-weight:600;color:#374151}
@media(max-width:380px){.val{font-size:22px}.log{height:160px}}
)DASHCSS";
static const char DASHBOARD_HTML_PART_B[] = R"DASH(</style>
</head>
<body>
<header>
  <div style="flex:1;min-width:160px">
    <h1>AutoLink Monitor <span class="role-pill empty" id="rolePill"></span></h1>
    <div class="sub" id="uptime">connecting&#x2026;</div>
  </div>
  <button class="btn rbt" id="rebootBtnTop" onclick="reboot()" title="Reboot device">&#9211; Reboot</button>
  <div class="lvl-group ping-only" id="modeGroup" role="radiogroup" aria-label="Fill mode" style="margin-right:8px">
    <label><input type="radio" name="mode" value="seq" id="modeSeq"><span>Sequential</span></label>
    <label><input type="radio" name="mode" value="rand" id="modeRand"><span>Random</span></label>
  </div>
  <div class="ping-only" id="startGroup" style="display:flex;flex-direction:column;align-items:stretch;margin-right:8px">
    <button class="btn pause ping-only" id="topPbtn" onclick="toggleMsgPause()">&#9654; Start</button>
    <label class="delay-lbl ping-only" for="delayMs" style="font-size:11px;color:#6b7280;margin-top:4px;text-align:center">delay ms</label>
    <select class="ping-only" id="delayMs" onchange="onDelayChange(this.value)" style="margin-top:2px;padding:2px 4px;font-size:12px;border-radius:4px;border:1px solid #d1d5db;background:#fff">
      <option value="0">0</option>
      <option value="10">10</option>
      <option value="50">50</option>
      <option value="100">100</option>
      <option value="500">500</option>
      <option value="1000">1000</option>
      <option value="5000">5000</option>
      <option value="10000">10000</option>
    </select>
  </div>
  <span class="pill swp" id="pill">SWP</span>
  <span class="pill" id="linkModePill" style="background:#e0e7ff;color:#3730a3">SYNC</span>
  <button class="btn" id="modeToggleBtn" onclick="toggleLinkMode()" title="Switch SYNC/ASYNC (reboots device)">&#8646; Toggle</button>
</header>
<main>
  <div class="alert" id="alert">Connection lost &#x2014; check power and WiFi</div>
  <div class="grid">
    <div class="card">
      <div class="lbl">TX Rate</div>
      <div class="val g" id="txbps">&#x2014;</div>
      <div class="hint" id="txtot">total &#x2014;</div>
    </div>
    <div class="card">
      <div class="lbl">RX Rate</div>
      <div class="val b" id="rxbps">&#x2014;</div>
      <div class="hint" id="rxtot">total &#x2014;</div>
    </div>
    <div class="card">
      <div class="lbl">Errors</div>
      <div class="val r" id="discon">&#x2014;</div>
      <div class="hint" id="lostmsgs">0 lost msgs</div>
      <div class="hint" id="errcnt">0 frame errors</div>
    </div>
    <div class="card">
      <div class="lbl">WiFi RSSI</div>
      <div class="val a" id="rssi">&#x2014;</div>
      <div class="hint" id="heap">heap &#x2014;</div>
      <div class="hint" id="baud">baud &#x2014;</div>
    </div>
  </div>
  <div class="row" style="margin-bottom:10px">
    <span class="section-lbl">Counters</span>
    <div class="btns">
      <button class="btn rst" id="rbtn" onclick="resetAll()">&#8635; Reset</button>
    </div>
  </div>
  <div class="row">
    <span class="section-lbl">Live Log</span>
    <div class="btns">
      <div class="lvl-group" id="lvlGroup" role="radiogroup" aria-label="Log level">
        <!-- "None" is intentionally not exposed: silencing the logger
             is unrecoverable without a reflash or NVS clear. The
             server also rejects lv=0 with a 400. -->
        <label><input type="radio" name="lvl" value="1"><span>Error</span></label>
        <label><input type="radio" name="lvl" value="2"><span>Warn</span></label>
        <label><input type="radio" name="lvl" value="3"><span>Info</span></label>
        <label><input type="radio" name="lvl" value="4"><span>Debug</span></label>
        <!-- Verbose above Debug: per-frame control traffic (Link
             sendFrame TX) that is too noisy for normal operation but
             useful for wire-trace forensics. -->
        <label><input type="radio" name="lvl" value="5"><span>Verbose</span></label>
      </div>
      <button class="btn" onclick="clearLog()">Clear</button>
      <button class="btn" id="cbtn" onclick="copyLog()">Copy</button>
      <button class="btn" id="sbtn" onclick="saveLog()" title="Download live log as ping.txt or pong.txt">Save</button>
      <button class="btn" id="pbtn" onclick="togglePause()">&#9646;&#9646; Pause</button>
      <button class="btn" onclick="openLogFull()" title="Maximize">&#x26F6;</button>
    </div>
  </div>
  <div class="log-wrap">
    <div class="log" id="log"></div>
    <div class="log-fill-bar" id="logFill"></div>
  </div>
  <div class="log-overlay" id="logOverlay">
    <div class="log-overlay-hdr">
      <span>Live Log (maximized)</span>
      <div class="btns">
        <div class="lvl-group" id="lvlGroup2" role="radiogroup" aria-label="Log level">
          <label><input type="radio" name="lvl2" value="1"><span>Error</span></label>
          <label><input type="radio" name="lvl2" value="2"><span>Warn</span></label>
          <label><input type="radio" name="lvl2" value="3"><span>Info</span></label>
          <label><input type="radio" name="lvl2" value="4"><span>Debug</span></label>
          <!-- Verbose in the overlay's log-level group too. -->
          <label><input type="radio" name="lvl2" value="5"><span>Verbose</span></label>
        </div>
        <button class="btn" onclick="clearLog()">Clear</button>
        <button class="btn" id="cbtn2" onclick="copyLog()">Copy</button>
        <button class="btn" id="pbtn2" onclick="togglePause()">&#9646;&#9646; Pause</button>
        <button class="btn log-overlay-close" onclick="closeLogFull()">Close</button>
      </div>
    </div>
    <div class="log" id="logFull"></div>
    <div class="log-fill-bar" id="logFillFull"></div>
  </div>
  <div class="footer"><span id="ver">v)DASH" AUTOLINK_VERSION R"DASH(</span> AutoLink Web Monitor &#x2014; <span id="host"></span></div>
</main>
<script>)DASH";
static const char DASHBOARD_JS[] = R"DASH(

console.log('[autolink] dashboard script loaded, HTML build v)DASH" AUTOLINK_VERSION R"DASH(');
console.log('[autolink] starting up…');

var logPaused=false,msgPaused=true,logFullOpen=false,lastSeq=0,fails=0,busy=false,currentLvl=null;
var currentMode=null;
var currentLinkMode='SYNC';

var deviceRole=null;

function fallbackCopy(text,b){
  var ta=document.createElement('textarea');
  ta.value=text;ta.style.position='fixed';ta.style.opacity='0';
  document.body.appendChild(ta);ta.focus();ta.select();
  var revertLabel=b.dataset.defaultLabel||b.textContent;
  if(!b.dataset.defaultLabel)b.dataset.defaultLabel=b.textContent;
  try{
    var ok=document.execCommand('copy');
    b.textContent=ok?'\u2713 Copied':'\u2717 Failed';
    console.log('[autolink] copy log: fallback path '+(ok?'succeeded':'failed'));
  }catch(e){
    b.textContent='\u2717 Failed';
    console.warn('[autolink] copy log: fallback threw '+(e&&e.message?e.message:e));
  }
  document.body.removeChild(ta);
  setTimeout(function(){b.textContent=revertLabel;},1200);
}

async function resetAll(){
  console.log('[autolink] button: reset (counters)');
  var b=document.getElementById('rbtn');
  b.textContent='\u2026';
  try{
    var r=await tfetch('/reset',{method:'POST'},5000);
    b.textContent=r.ok?'\u2713 Done':'\u2717 Err';
    console.log('[autolink] reset result: '+(r.ok?'OK':'fail http '+(r.status||'?')));
  }catch(e){
    b.textContent='\u2717 Err';
    console.warn('[autolink] reset failed: '+(e&&e.message?e.message:e));
  }
  setTimeout(function(){b.textContent='\u21bb Reset';},1200);
}

async function reboot(){
  if(!confirm('Reboot the device now? The link will drop and reconnect in a few seconds.'))return;
  console.log('[autolink] button: reboot (device reset requested)');
  clearLog();lastSeq=0;
  var b=document.getElementById('rebootBtnTop');
  b.textContent='Rebooting\u2026';
  try{
    var r=await tfetch('/reboot',{method:'POST'},5000);
    console.log('[autolink] reboot ack: '+(r&&r.ok?'OK':'fail http '+(r&&r.status||'?')));
  }catch(e){
    console.log('[autolink] reboot: device disconnected (expected)');
  }
  show('alert');
  var tries=0;
  var iv=setInterval(async function(){
    tries++;
    try{
      var r=await tfetch('/stats',null,5000);
      if(r.ok){
        clearInterval(iv);
        console.log('[autolink] reboot: device back online after '+(tries+1)+' s, reloading');
        location.reload();
      }
    }catch(e){}
    if(tries>30){
      clearInterval(iv);
      console.warn('[autolink] reboot: device did not come back online within 30 s');
    }
  },1000);
}

function updateFillBar(){
  var t=document.getElementById('log').textContent;
  var pct=Math.min(100,Math.round(t.length/5000))+'%';
  ['logFill','logFillFull'].forEach(function(id){var b=document.getElementById(id);if(b)b.style.setProperty('--pct',pct);});
}
function openLogFull(){
  logFullOpen=true;
  var o=document.getElementById('logOverlay');o.classList.add('open');
  var dst=document.getElementById('logFull');
  dst.innerHTML=document.getElementById('log').innerHTML;
  dst.scrollTop=dst.scrollHeight;updateFillBar();
  console.log('[autolink] button: log overlay opened ('+document.getElementById('log').children.length+' entries)');
}
function closeLogFull(){
  logFullOpen=false;
  document.getElementById('logOverlay').classList.remove('open');
  console.log('[autolink] button: log overlay closed');
}
function appendLog(sev,seq,text){
  if(seq+1>lastSeq)lastSeq=seq+1;
  if(logPaused)return;
  function addTo(p){
    var atEnd=p.scrollHeight-p.scrollTop<=p.clientHeight+12;
    var d=document.createElement('div');d.className=sev;d.textContent=text;p.appendChild(d);
    if(p.textContent.length>500000){while(p.children.length>1&&p.textContent.length>400000)p.removeChild(p.firstChild);}
    if(atEnd)p.scrollTop=p.scrollHeight;
  }
  addTo(document.getElementById('log'));
  if(logFullOpen)addTo(document.getElementById('logFull'));
  updateFillBar();

  try{if(localStorage.verbose==='1')console.log('[autolink] log['+seq+'] '+sev+' '+text);}catch(_){}
}

function tfetch(url,opts,ms){
  var c=new AbortController();
  var id=setTimeout(function(){c.abort();},ms||5000);
  var o=Object.assign({signal:c.signal},opts||{});
  var method=(opts&&opts.method)||'GET';
  console.log('[autolink] '+method+' '+url+' (timeout '+(ms||5000)+'ms)');
  return fetch(url,o).then(function(r){
      clearTimeout(id);
      console.log('[autolink] '+method+' '+url+' -> '+r.status);
      return r;
    },function(e){
      clearTimeout(id);
      console.warn('[autolink] '+method+' '+url+' FAILED: '+(e&&e.message?e.message:e));
      throw e;
    });
}

function bps(n){if(n>=1048576)return(n/1048576).toFixed(1)+' MB/s';if(n>=1024)return(n/1024).toFixed(1)+' KB/s';return n+' B/s';}
function bytes(n){if(n>=1073741824)return(n/1073741824).toFixed(2)+' GB';if(n>=1048576)return(n/1048576).toFixed(2)+' MB';if(n>=1024)return(n/1024).toFixed(1)+' KB';return n+' B';}
function hms(s){return[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(function(x){return('0'+x).slice(-2);}).join(':');}

function set(id,v){var e=document.getElementById(id);if(e)e.textContent=v;}
function setPill(st){
  var p=document.getElementById('pill');
  if(!p)return;
  p.textContent=st;p.className='pill '+(st==='OK'?'ok':st==='SWP'?'swp':st==='LCK'?'lck':'');
}
function show(id){var e=document.getElementById(id);if(e)e.style.display='block';}
function hide(id){var e=document.getElementById(id);if(e)e.style.display='none';}

function clearLog(){
  var n=document.getElementById('log').children.length;
  ['log','logFull'].forEach(function(id){var e=document.getElementById(id);if(e)e.innerHTML='';});
  updateFillBar();
  console.log('[autolink] button: clear log (cleared '+n+' entries)');
}
// Walk the live log's child nodes (each line
// is a <div>) and join with \n + trailing
// newline so Copy and Save emit unix-line-
// delimited plain text. textContent on the
// parent renders with no line breaks at all
// (block boundaries collapse).
function al_logAsText(){
  var log=document.getElementById('log');
  if(!log)return'';
  var parts=[];
  for(var i=0;i<log.children.length;i++){
    var c=log.children[i];
    if(c.textContent)parts.push(c.textContent);
  }
  return parts.join('\n')+(parts.length?'\n':'');
}
function copyLog(){
  var t=al_logAsText();
  var bytes=t.length;
  // Even with an empty log we still attempt
  // the clipboard write so the button label
  // flips to "Copied" + reverts on the
  // standard path. textContent alone is
  // non-empty from inline-block whitespace;
  // tests pin the label-revert behavior.
  if(navigator.clipboard){
    navigator.clipboard.writeText(t).then(function(){
      var b=document.getElementById('cbtn');
      b.textContent='\u2713 Copied';
      setTimeout(function(){b.textContent='Copy';},1200);
      console.log('[autolink] button: copy log ('+bytes+' bytes copied to clipboard)');
    }).catch(function(e){
      fallbackCopy(t,document.getElementById('cbtn'));
      console.warn('[autolink] copy log: clipboard API failed ('+(e&&e.message?e.message:e)+'), used fallback');
    });
  }else{
    fallbackCopy(t,document.getElementById('cbtn'));
    console.log('[autolink] button: copy log (fallback path, '+bytes+' bytes)');
  }
}

function saveLog(){
  var t=al_logAsText();
  if(!t.length){
    console.warn('[autolink] save log: log is empty, nothing to save');
    return;
  }
  var name=(deviceRole==='Pong'?'pong.txt':(deviceRole==='Ping'?'ping.txt':'autolink.txt'));
  try{
    var blob=new Blob([t],{type:'text/plain;charset=utf-8'});
    var url=URL.createObjectURL(blob);
    var a=document.createElement('a');
    a.href=url;
    a.download=name;
    a.style.display='none';
    document.body.appendChild(a);
    a.click();
    setTimeout(function(){document.body.removeChild(a);URL.revokeObjectURL(url);},200);
    var b=document.getElementById('sbtn');
    b.textContent='\u2713 Saved';
    setTimeout(function(){b.textContent='Save';},1200);
    console.log('[autolink] button: save log ('+t.length+' bytes -> '+name+')');
  }catch(e){
    console.warn('[autolink] save log failed: '+(e&&e.message?e.message:e));
  }
}
function togglePause(){
  logPaused=!logPaused;
  var lbl=logPaused?'\u25b6 Resume':'\u25ae\u25ae Pause';
  ['pbtn','pbtn2'].forEach(function(id){var b=document.getElementById(id);if(b)b.textContent=lbl;});
  console.log('[autolink] button: log scroll '+(logPaused?'paused':'resumed'));
}

async function toggleMsgPause(){
  if(deviceRole!=='Ping'){
    console.log('[autolink] toggleMsgPause ignored — device role is '+deviceRole+' (not Ping)');
    return;
  }
  msgPaused=!msgPaused;
  applyMsgPauseLabel();
  console.log('[autolink] button: message pause -> '+msgPaused+' (sending /pausemsg)');
  try{
    var r=await tfetch('/pausemsg?p='+(msgPaused?'1':'0'),{method:'POST'},5000);
    if(!r.ok){
      console.warn('[autolink] /pausemsg returned '+r.status+' — local UI shows last-known state until /stats reconciles');
    }
  } catch(e){
    console.warn('[autolink] /pausemsg fetch failed: '+(e&&e.message?e.message:e)+' — local UI shows last-known state until /stats reconciles');
  }
}
function applyMsgPauseLabel(){
  var b=document.getElementById('topPbtn');
  if(b){
    if(msgPaused){b.innerHTML='\u25b6 Start';b.className='btn pause on';}
    else{b.innerHTML='\u25ae\u25ae Pause';b.className='btn pause';}
  }
}

// SYNC/ASYNC link-mode toggle. Persisted to NVS on the device;
// the firmware reboots on success. The dashboard reconciles the
// pill from /stats once the device comes back.
async function toggleLinkMode(){
  var cur=(typeof currentLinkMode!=='undefined'&&currentLinkMode)?currentLinkMode:'SYNC';
  var nxt=(cur==='SYNC')?'ASYNC':'SYNC';
  if(!confirm('Switch link mode from '+cur+' to '+nxt+'? The device will reboot.'))return;
  var b=document.getElementById('modeToggleBtn');
  if(b){b.textContent='\u2026';b.disabled=true;}
  console.log('[autolink] button: link mode toggle '+cur+' -> '+nxt+' (sending /mode/toggle)');
  try{
    var r=await tfetch('/mode/toggle',{method:'POST'},5000);
    if(r.ok){
      var body=await r.text();
      console.log('[autolink] /mode/toggle ack: '+body);
      clearLog();lastSeq=0;
      show('alert');
      var tries=0;
      var iv=setInterval(async function(){
        tries++;
        try{
          var rr=await tfetch('/stats',null,5000);
          if(rr.ok){clearInterval(iv);console.log('[autolink] mode toggle: device back online after '+(tries+1)+' s, reloading');location.reload();}
        }catch(_){}
        if(tries>30){clearInterval(iv);console.warn('[autolink] mode toggle: device did not come back online within 30 s');}
      },1000);
    }else{
      if(b){b.textContent='\u2717 Err';setTimeout(function(){b.textContent='\u21c6 Toggle';b.disabled=false;},1500);}
      console.warn('[autolink] /mode/toggle returned '+r.status);
    }
  }catch(e){
    if(b){b.textContent='\u2717 Err';setTimeout(function(){b.textContent='\u21c6 Toggle';b.disabled=false;},1500);}
    console.warn('[autolink] /mode/toggle fetch failed: '+(e&&e.message?e.message:e));
  }
}
function applyLinkModeLabel(m){
  var p=document.getElementById('linkModePill');
  if(p){p.textContent=m;}
  currentLinkMode=m;
}

// Cookie helpers: persist the last delay-ms
// choice across reloads.
function al_cookie_set(name, val, days){
  var d=new Date();
  d.setTime(d.getTime()+(days||365)*24*60*60*1000);
  document.cookie=name+'='+encodeURIComponent(val)+
    ';expires='+d.toUTCString()+';path=/;SameSite=Lax';
}
function al_cookie_get(name){
  var m=document.cookie.match(new RegExp('(?:^|; )'+name+'=([^;]*)'));
  return m?decodeURIComponent(m[1]):null;
}

async function onDelayChange(val){
  var ms=parseInt(val,10);
  if(isNaN(ms)||ms<0)ms=0;
  al_cookie_set('al_delay_ms', String(ms));
  console.log('[autolink] delay widget: txDelayMs='+ms+' (sending /delay, cookie saved)');
  try{
    var r=await tfetch('/delay?ms='+ms,{method:'POST'},5000);
    if(!r.ok){
      console.warn('[autolink] /delay returned '+r.status+' — local UI shows last-known state until /stats reconciles');
    }
  }catch(e){
    console.warn('[autolink] /delay fetch failed: '+(e&&e.message?e.message:e)+' — local UI shows last-known state until /stats reconciles');
  }
}

function bindLvlGroup(name){
  document.querySelectorAll('input[name='+name+']').forEach(function(r){
    r.addEventListener('change',async function(){
      if(!this.checked)return;
      var lv=this.value;
      console.log('[autolink] button: log level change -> lv='+lv);
      try{
        var r2=await tfetch('/level?lv='+encodeURIComponent(lv),{method:'POST'},5000);
        if(r2.ok){
          currentLvl=lv;
          highlightLvl();
          console.log('[autolink] log level set: lv='+lv+' (firmware applied)');
        }else{
          console.warn('[autolink] log level set: firmware rejected lv='+lv+' (http '+(r2.status||'?')+')');
        }
      }catch(e){
        console.warn('[autolink] log level set failed: '+(e&&e.message?e.message:e));
      }
    });
  });
}
bindLvlGroup('lvl');
bindLvlGroup('lvl2');
function highlightLvl(){
  document.querySelectorAll('.lvl-group label').forEach(function(l){
    var inp=l.querySelector('input');
    l.classList.toggle('on',inp&&inp.value===currentLvl);
  });
}

function bindModeGroup(name){
  document.querySelectorAll('input[name='+name+']').forEach(function(r){
    r.addEventListener('change',async function(){
      if(!this.checked)return;
      var m=this.value;
      console.log('[autolink] button: fill mode change -> m='+m);
      try{
        var r2=await tfetch('/mode?m='+encodeURIComponent(m),{method:'POST'},5000);
        if(r2.ok){
          currentMode=m;
          highlightMode();
          console.log('[autolink] fill mode set: m='+m+' (firmware applied)');
        }else{
          console.warn('[autolink] fill mode set: firmware rejected m='+m+' (http '+(r2.status||'?')+', likely Pong side)');
        }
      }catch(e){
        console.warn('[autolink] fill mode set failed: '+(e&&e.message?e.message:e));
      }
    });
  });
}
bindModeGroup('mode');
function highlightMode(){
  document.querySelectorAll('.lvl-group label').forEach(function(l){
    var inp=l.querySelector('input');
    if(inp&&inp.name==='mode')l.classList.toggle('on',inp.value===currentMode);
  });
}

async function poll(){
  if(busy)return;
  busy=true;

  try{
    try{
    var r=await tfetch('/stats',null,5000);
    if(!r.ok)throw 0;
    var d=await r.json();

    set('txbps',bps(d.txBps));
    set('txtot','total '+bytes(d.txTotal));
    set('rxbps',bps(d.rxBps));
    set('rxtot','total '+bytes(d.rxTotal));
    set('discon', d.errTotal);
    var lm=d.lostMsgs||0;
    set('lostmsgs', lm + (lm===1?' lost msg':' lost msgs'));
    var ec=d.errCount||0;
    set('errcnt', ec + (ec===1?' frame error':' frame errors'));
    set('rssi',d.rssi+' dBm');
    set('heap','heap '+bytes(d.freeHeap));
    if(d.state==='OK'){
      set('baud', d.baudRate ? d.baudRate.toLocaleString()+' baud' : '?');
    } else if(d.state==='SWP'){
      set('baud', (d.baudRate ? d.baudRate.toLocaleString() : '?')+' \u21c4 sweeping');
    } else if(d.state==='LCK'){
      set('baud', (d.baudRate ? d.baudRate.toLocaleString() : '?')+' \u21c4 locking');
    } else {
      set('baud', d.baudRate ? d.baudRate.toLocaleString()+' baud' : '\u2014');
    }
    set('uptime','up '+hms(d.uptimeS));
    setPill(d.state);
    if(d.version){
      document.getElementById('ver').textContent='v'+d.version;
      if(!window._autolinkLoggedVer){
        window._autolinkLoggedVer=true;
        console.log('[autolink] device firmware reports v'+d.version);
      }
    }

    var rp=document.getElementById('rolePill');
    if(rp){
      if(d.role&&d.role.length){
        rp.textContent=d.role;
        rp.classList.remove('empty');
      }else{
        rp.textContent='';
        rp.classList.add('empty');
      }
    }

    if(d.role==='Ping'){
      deviceRole='Ping';
      document.body.setAttribute('data-role','ping');
    }else if(d.role==='Pong'){
      deviceRole='Pong';
      document.body.setAttribute('data-role','pong');

      document.querySelectorAll('.ping-only').forEach(function(el){
        el.style.display='none';
      });
    }

    if(d.lvl!==undefined&&d.lvl!==null&&String(d.lvl)!==currentLvl){
      currentLvl=String(d.lvl);
      document.querySelectorAll('input[name=lvl][value="'+currentLvl+'"], input[name=lvl2][value="'+currentLvl+'"]').forEach(function(r){r.checked=true;});
      highlightLvl();
    }

    if(d.mode!==undefined&&d.mode!==null){
      var m=d.mode===1?'rand':'seq';
      if(m!==currentMode){
        currentMode=m;
        var inp=document.querySelector('input[name=mode][value="'+m+'"]');
        if(inp)inp.checked=true;
        highlightMode();
      }
    }

    if(d.linkModeLabel!==undefined&&d.linkModeLabel!==null){
      if(d.linkModeLabel!==currentLinkMode){
        applyLinkModeLabel(d.linkModeLabel);
        console.log('[autolink] /stats linkModeLabel='+d.linkModeLabel+' — reconciled mode pill');
      }
    }

    if(d.msgPaused!==undefined&&d.msgPaused!==null){
      var devPaused=d.msgPaused===1;
      if(devPaused!==msgPaused){
        msgPaused=devPaused;
        applyMsgPauseLabel();
        console.log('[autolink] /stats msgPaused='+devPaused+' — reconciled button label');
      }
    }

    if(d.txDelayMs!==undefined&&d.txDelayMs!==null){
      var sel=document.getElementById('delayMs');
      if(sel){
        var devMs=String(d.txDelayMs);
        // Don't fight the user: if they just clicked the dropdown,
        // /stats will catch up next poll. Only update if it differs
        // and the dropdown isn't currently focused.
        if(devMs!==sel.value&&document.activeElement!==sel){
          sel.value=devMs;
          console.log('[autolink] /stats txDelayMs='+d.txDelayMs+' — synced dropdown (cookie unchanged)');
        }
      }
    }
    fails=0;hide('alert');
    console.log('[autolink] /stats OK state='+d.state+' rxBps='+d.rxBps);
    }catch(e){
      var ec=(e&&e.code)||'';
      var em=(e&&e.message)||String(e);
      console.warn('[autolink] /stats poll failed #'+fails+' code='+ec+' msg='+em);
      if(++fails>=3){
        show('alert');
        if(/^(NETWORKERR|ERR_CONNECTION|ECONNREFUSED|ECONNRESET|ETIMEDOUT)/.test(ec)){
          if(fails>=8){try{location.reload();}catch(_){}}
        }
      }
    }
    try{
    var r2=await tfetch('/logs?since='+lastSeq,null,5000);
    if(!r2.ok)throw new Error('http '+r2.status);
    var d2=await r2.json();
    if(lastSeq===0 && d2.head!==undefined){
      lastSeq=d2.head;
    }else{
      var got=d2.lines?d2.lines.length:0;
      if(got>0)console.log('[autolink] /logs '+got+' new line(s) (since='+lastSeq+')');
      d2.lines.forEach(function(l){appendLog(l.sev,l.seq,l.text);});
    }
    }catch(e){
      console.warn('[autolink] /logs poll failed: '+((e&&e.message)||e));
    }
  }finally{
    busy=false;
  }
}

document.addEventListener('visibilitychange',function(){if(!document.hidden){console.log('[autolink] tab visible — resuming poll');poll();}});
setInterval(poll,1000);
poll().then(function(){
  var _role=document.body.getAttribute('data-role')||'unknown';
  var _state=document.getElementById('pill')?document.getElementById('pill').textContent:'?';
  console.log('[autolink] startup OK — dashboard connected to firmware v)DASH" AUTOLINK_VERSION R"DASH( role='+_role+' state='+_state);
  // Rehydrate delay widget: cookie value wins if set, else
  // firmware's current txDelayMs (from /stats). Cookie is the
  // user-sticky default so a reload restores the last choice.
  var _sel=document.getElementById('delayMs');
  if(_sel){
    var _ck=al_cookie_get('al_delay_ms');
    if(_ck!==null){
      _sel.value=_ck;
      onDelayChange(_ck);
      console.log('[autolink] delay widget: rehydrated from cookie='+_ck);
    } else {
      console.log('[autolink] delay widget: no cookie, using firmware default');
    }
  }
}).catch(function(e){
  console.error('[autolink] startup FAILED: '+(e&&e.message?e.message:e), '— dashboard will retry every 1 s');
});
)DASH";
static const char DASHBOARD_HTML_PART_C[] = R"DASH(</script>
</body>
</html>)DASH";
// Adjacent string-literal concatenation is a compile-time
// operation: sizeof(DASHBOARD_HTML) is the sum of the five
// parts (plus any AUTOLINK_VERSION tokens, expanded by the
// preprocessor). httpd's chunked-send loop keeps its length
// contract without a runtime strlen().
static const char DASHBOARD_HTML[] = R"DASH(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
<title>AutoLink Monitor</title>
<style>)DASH" R"DASHCSS(
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f0f2f5;color:#111827;min-height:100vh}
/* Hide Ping-only controls (fill mode radio, pause/start) when the
   device is a Pong. Pong is receive-only, so these are meaningless
   affordances. The body[data-role="pong"] attribute is set by the
   /stats poll handler once we know the role. Default: show
   everything (until the first /stats response lands, the user
   doesn't yet know if they're looking at Ping or Pong). */
body[data-role="pong"] .ping-only{display:none}
header{background:#ffffff;padding:14px 18px;display:flex;align-items:center;justify-content:space-between;border-bottom:2px solid #d1d5db;position:sticky;top:0;z-index:10;box-shadow:0 2px 8px rgba(0,0,0,.08);gap:10px;flex-wrap:wrap}
h1{font-size:18px;font-weight:700;letter-spacing:.2px}
.sub{font-size:13px;color:#6b7280;margin-top:3px}
.pill{padding:6px 16px;border-radius:20px;font-size:13px;font-weight:700;letter-spacing:.5px;transition:background .3s,color .3s}
.ok{background:#d1fae5;color:#065f46}
.swp{background:#fee2e2;color:#991b1b}
.lck{background:#fef9c3;color:#92400e}
main{padding:14px;max-width:540px;margin:0 auto}
.alert{background:#fee2e2;border:1px solid #f87171;border-radius:10px;padding:10px 14px;color:#991b1b;font-size:14px;text-align:center;margin-bottom:12px;display:none}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:14px}
.card{background:#ffffff;border:1px solid #d1d5db;border-radius:12px;padding:14px;box-shadow:0 1px 3px rgba(0,0,0,.06)}
.lbl{font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.9px;margin-bottom:7px;font-weight:600}
.val{font-size:26px;font-weight:700;font-variant-numeric:tabular-nums;line-height:1.1}
.g{color:#059669}.b{color:#2563eb}.r{color:#dc2626}.a{color:#7c3aed}
.hint{font-size:11px;color:#6b7280;margin-top:3px;font-variant-numeric:tabular-nums}
.row{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:8px;flex-wrap:wrap}
.section-lbl{font-size:12px;font-weight:700;color:#374151;text-transform:uppercase;letter-spacing:.6px}
.btns{display:flex;gap:6px;flex-wrap:wrap;align-items:center}
.btn{font:600 12px -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;padding:7px 12px;border:1px solid #d1d5db;background:#fff;border-radius:8px;cursor:pointer;color:#374151;transition:background .15s;-webkit-tap-highlight-color:transparent;user-select:none}
.btn:hover{background:#f3f4f6}
.btn.on{background:#dbeafe;color:#1d4ed8;border-color:#93c5fd}
.btn.pause.on{background:#fef3c7;color:#92400e;border-color:#fcd34d}
.btn.rst{color:#dc2626;border-color:#fca5a5}
.btn.rst:hover{background:#fef2f2}
.btn.rbt{color:#7c2d12;border-color:#fdba74;background:#fff7ed}
.btn.rbt:hover{background:#ffedd5}
.lvl-group{display:inline-flex;border:1px solid #d1d5db;border-radius:8px;overflow:hidden;background:#f9fafb;flex-wrap:wrap}
.lvl-group label{display:flex;align-items:center;gap:4px;padding:6px 10px;font-size:12px;font-weight:600;color:#374151;cursor:pointer;-webkit-tap-highlight-color:transparent;border-right:1px solid #d1d5db;user-select:none}
.lvl-group label:last-child{border-right:none}
.lvl-group input[type=radio]{margin:0;accent-color:#2563eb}
.lvl-group label.on{background:#dbeafe;color:#1d4ed8}
.role-pill{background:#e0e7ff;color:#3730a3;padding:3px 10px;border-radius:12px;font-size:13px;font-weight:600;letter-spacing:.3px;margin-left:6px}
.role-pill.empty{display:none}
.log-wrap{position:relative}
.log{background:#1f2937;color:#e5e7eb;font:11px ui-monospace,Menlo,Consolas,monospace;border-radius:10px;padding:10px 12px;height:200px;overflow-y:auto;line-height:1.5;border:1px solid #d1d5db}
.log>div{white-space:pre-wrap;word-break:break-all}
.log .E{color:#fca5a5}.log .W{color:#fcd34d}.log .I{color:#93c5fd}.log .D{color:#9ca3af}.log .V{color:#c4b5fd}
.log-fill-bar{height:5px;border-radius:0 0 8px 8px;background:linear-gradient(to right,#22c55e var(--pct,0%),#e5e7eb var(--pct,0%));border:1px solid #d1d5db;border-top:none;transition:background 0.3s}
.log-overlay{display:none;position:fixed;inset:0;z-index:9999;background:#fff;flex-direction:column}
.log-overlay.open{display:flex}
.log-overlay .log{flex:1;height:auto;border-radius:0;border:none;border-bottom:1px solid #d1d5db}
.log-overlay .log-fill-bar{border-radius:0;border:none;border-top:1px solid #e5e7eb}
.log-overlay-hdr{display:flex;align-items:center;justify-content:space-between;padding:8px 14px;border-bottom:1px solid #d1d5db;background:#f9fafb}
.log-overlay-hdr>span{font-weight:600;font-size:14px}
.log-overlay-close{padding:6px 12px;border:1px solid #d1d5db;background:#fff;border-radius:8px;font:600 12px -apple-system,sans-serif;cursor:pointer}
.footer{text-align:center;font-size:11px;color:#6b7280;padding:12px 8px 24px}
.footer span{font-weight:600;color:#374151}
@media(max-width:380px){.val{font-size:22px}.log{height:160px}}
)DASHCSS" R"DASH(</style>
</head>
<body>
<header>
  <div style="flex:1;min-width:160px">
    <h1>AutoLink Monitor <span class="role-pill empty" id="rolePill"></span></h1>
    <div class="sub" id="uptime">connecting&#x2026;</div>
  </div>
  <button class="btn rbt" id="rebootBtnTop" onclick="reboot()" title="Reboot device">&#9211; Reboot</button>
  <div class="lvl-group ping-only" id="modeGroup" role="radiogroup" aria-label="Fill mode" style="margin-right:8px">
    <label><input type="radio" name="mode" value="seq" id="modeSeq"><span>Sequential</span></label>
    <label><input type="radio" name="mode" value="rand" id="modeRand"><span>Random</span></label>
  </div>
  <div class="ping-only" id="startGroup" style="display:flex;flex-direction:column;align-items:stretch;margin-right:8px">
    <button class="btn pause ping-only" id="topPbtn" onclick="toggleMsgPause()">&#9654; Start</button>
    <label class="delay-lbl ping-only" for="delayMs" style="font-size:11px;color:#6b7280;margin-top:4px;text-align:center">delay ms</label>
    <select class="ping-only" id="delayMs" onchange="onDelayChange(this.value)" style="margin-top:2px;padding:2px 4px;font-size:12px;border-radius:4px;border:1px solid #d1d5db;background:#fff">
      <option value="0">0</option>
      <option value="10">10</option>
      <option value="50">50</option>
      <option value="100">100</option>
      <option value="500">500</option>
      <option value="1000">1000</option>
      <option value="5000">5000</option>
      <option value="10000">10000</option>
    </select>
  </div>
  <span class="pill swp" id="pill">SWP</span>
  <span class="pill" id="linkModePill" style="background:#e0e7ff;color:#3730a3">SYNC</span>
  <button class="btn" id="modeToggleBtn" onclick="toggleLinkMode()" title="Switch SYNC/ASYNC (reboots device)">&#8646; Toggle</button>
</header>
<main>
  <div class="alert" id="alert">Connection lost &#x2014; check power and WiFi</div>
  <div class="grid">
    <div class="card">
      <div class="lbl">TX Rate</div>
      <div class="val g" id="txbps">&#x2014;</div>
      <div class="hint" id="txtot">total &#x2014;</div>
    </div>
    <div class="card">
      <div class="lbl">RX Rate</div>
      <div class="val b" id="rxbps">&#x2014;</div>
      <div class="hint" id="rxtot">total &#x2014;</div>
    </div>
    <div class="card">
      <div class="lbl">Errors</div>
      <div class="val r" id="discon">&#x2014;</div>
      <div class="hint" id="lostmsgs">0 lost msgs</div>
      <div class="hint" id="errcnt">0 frame errors</div>
    </div>
    <div class="card">
      <div class="lbl">WiFi RSSI</div>
      <div class="val a" id="rssi">&#x2014;</div>
      <div class="hint" id="heap">heap &#x2014;</div>
      <div class="hint" id="baud">baud &#x2014;</div>
    </div>
  </div>
  <div class="row" style="margin-bottom:10px">
    <span class="section-lbl">Counters</span>
    <div class="btns">
      <button class="btn rst" id="rbtn" onclick="resetAll()">&#8635; Reset</button>
    </div>
  </div>
  <div class="row">
    <span class="section-lbl">Live Log</span>
    <div class="btns">
      <div class="lvl-group" id="lvlGroup" role="radiogroup" aria-label="Log level">
        <!-- "None" is intentionally not exposed: silencing the logger
             is unrecoverable without a reflash or NVS clear. The
             server also rejects lv=0 with a 400. -->
        <label><input type="radio" name="lvl" value="1"><span>Error</span></label>
        <label><input type="radio" name="lvl" value="2"><span>Warn</span></label>
        <label><input type="radio" name="lvl" value="3"><span>Info</span></label>
        <label><input type="radio" name="lvl" value="4"><span>Debug</span></label>
        <!-- Verbose above Debug: per-frame control traffic (Link
             sendFrame TX) that is too noisy for normal operation but
             useful for wire-trace forensics. -->
        <label><input type="radio" name="lvl" value="5"><span>Verbose</span></label>
      </div>
      <button class="btn" onclick="clearLog()">Clear</button>
      <button class="btn" id="cbtn" onclick="copyLog()">Copy</button>
      <button class="btn" id="sbtn" onclick="saveLog()" title="Download live log as ping.txt or pong.txt">Save</button>
      <button class="btn" id="pbtn" onclick="togglePause()">&#9646;&#9646; Pause</button>
      <button class="btn" onclick="openLogFull()" title="Maximize">&#x26F6;</button>
    </div>
  </div>
  <div class="log-wrap">
    <div class="log" id="log"></div>
    <div class="log-fill-bar" id="logFill"></div>
  </div>
  <div class="log-overlay" id="logOverlay">
    <div class="log-overlay-hdr">
      <span>Live Log (maximized)</span>
      <div class="btns">
        <div class="lvl-group" id="lvlGroup2" role="radiogroup" aria-label="Log level">
          <label><input type="radio" name="lvl2" value="1"><span>Error</span></label>
          <label><input type="radio" name="lvl2" value="2"><span>Warn</span></label>
          <label><input type="radio" name="lvl2" value="3"><span>Info</span></label>
          <label><input type="radio" name="lvl2" value="4"><span>Debug</span></label>
          <!-- Verbose in the overlay's log-level group too. -->
          <label><input type="radio" name="lvl2" value="5"><span>Verbose</span></label>
        </div>
        <button class="btn" onclick="clearLog()">Clear</button>
        <button class="btn" id="cbtn2" onclick="copyLog()">Copy</button>
        <button class="btn" id="pbtn2" onclick="togglePause()">&#9646;&#9646; Pause</button>
        <button class="btn log-overlay-close" onclick="closeLogFull()">Close</button>
      </div>
    </div>
    <div class="log" id="logFull"></div>
    <div class="log-fill-bar" id="logFillFull"></div>
  </div>
  <div class="footer"><span id="ver">v)DASH" AUTOLINK_VERSION R"DASH(</span> AutoLink Web Monitor &#x2014; <span id="host"></span></div>
</main>
<script>)DASH" R"DASH(

console.log('[autolink] dashboard script loaded, HTML build v)DASH" AUTOLINK_VERSION R"DASH(');
console.log('[autolink] starting up…');

var logPaused=false,msgPaused=true,logFullOpen=false,lastSeq=0,fails=0,busy=false,currentLvl=null;
var currentMode=null;
var currentLinkMode='SYNC';

var deviceRole=null;

function fallbackCopy(text,b){
  var ta=document.createElement('textarea');
  ta.value=text;ta.style.position='fixed';ta.style.opacity='0';
  document.body.appendChild(ta);ta.focus();ta.select();
  var revertLabel=b.dataset.defaultLabel||b.textContent;
  if(!b.dataset.defaultLabel)b.dataset.defaultLabel=b.textContent;
  try{
    var ok=document.execCommand('copy');
    b.textContent=ok?'\u2713 Copied':'\u2717 Failed';
    console.log('[autolink] copy log: fallback path '+(ok?'succeeded':'failed'));
  }catch(e){
    b.textContent='\u2717 Failed';
    console.warn('[autolink] copy log: fallback threw '+(e&&e.message?e.message:e));
  }
  document.body.removeChild(ta);
  setTimeout(function(){b.textContent=revertLabel;},1200);
}

async function resetAll(){
  console.log('[autolink] button: reset (counters)');
  var b=document.getElementById('rbtn');
  b.textContent='\u2026';
  try{
    var r=await tfetch('/reset',{method:'POST'},5000);
    b.textContent=r.ok?'\u2713 Done':'\u2717 Err';
    console.log('[autolink] reset result: '+(r.ok?'OK':'fail http '+(r.status||'?')));
  }catch(e){
    b.textContent='\u2717 Err';
    console.warn('[autolink] reset failed: '+(e&&e.message?e.message:e));
  }
  setTimeout(function(){b.textContent='\u21bb Reset';},1200);
}

async function reboot(){
  if(!confirm('Reboot the device now? The link will drop and reconnect in a few seconds.'))return;
  console.log('[autolink] button: reboot (device reset requested)');
  clearLog();lastSeq=0;
  var b=document.getElementById('rebootBtnTop');
  b.textContent='Rebooting\u2026';
  try{
    var r=await tfetch('/reboot',{method:'POST'},5000);
    console.log('[autolink] reboot ack: '+(r&&r.ok?'OK':'fail http '+(r&&r.status||'?')));
  }catch(e){
    console.log('[autolink] reboot: device disconnected (expected)');
  }
  show('alert');
  var tries=0;
  var iv=setInterval(async function(){
    tries++;
    try{
      var r=await tfetch('/stats',null,5000);
      if(r.ok){
        clearInterval(iv);
        console.log('[autolink] reboot: device back online after '+(tries+1)+' s, reloading');
        location.reload();
      }
    }catch(e){}
    if(tries>30){
      clearInterval(iv);
      console.warn('[autolink] reboot: device did not come back online within 30 s');
    }
  },1000);
}

function updateFillBar(){
  var t=document.getElementById('log').textContent;
  var pct=Math.min(100,Math.round(t.length/5000))+'%';
  ['logFill','logFillFull'].forEach(function(id){var b=document.getElementById(id);if(b)b.style.setProperty('--pct',pct);});
}
function openLogFull(){
  logFullOpen=true;
  var o=document.getElementById('logOverlay');o.classList.add('open');
  var dst=document.getElementById('logFull');
  dst.innerHTML=document.getElementById('log').innerHTML;
  dst.scrollTop=dst.scrollHeight;updateFillBar();
  console.log('[autolink] button: log overlay opened ('+document.getElementById('log').children.length+' entries)');
}
function closeLogFull(){
  logFullOpen=false;
  document.getElementById('logOverlay').classList.remove('open');
  console.log('[autolink] button: log overlay closed');
}
function appendLog(sev,seq,text){
  if(seq+1>lastSeq)lastSeq=seq+1;
  if(logPaused)return;
  function addTo(p){
    var atEnd=p.scrollHeight-p.scrollTop<=p.clientHeight+12;
    var d=document.createElement('div');d.className=sev;d.textContent=text;p.appendChild(d);
    if(p.textContent.length>500000){while(p.children.length>1&&p.textContent.length>400000)p.removeChild(p.firstChild);}
    if(atEnd)p.scrollTop=p.scrollHeight;
  }
  addTo(document.getElementById('log'));
  if(logFullOpen)addTo(document.getElementById('logFull'));
  updateFillBar();

  try{if(localStorage.verbose==='1')console.log('[autolink] log['+seq+'] '+sev+' '+text);}catch(_){}
}

function tfetch(url,opts,ms){
  var c=new AbortController();
  var id=setTimeout(function(){c.abort();},ms||5000);
  var o=Object.assign({signal:c.signal},opts||{});
  var method=(opts&&opts.method)||'GET';
  console.log('[autolink] '+method+' '+url+' (timeout '+(ms||5000)+'ms)');
  return fetch(url,o).then(function(r){
      clearTimeout(id);
      console.log('[autolink] '+method+' '+url+' -> '+r.status);
      return r;
    },function(e){
      clearTimeout(id);
      console.warn('[autolink] '+method+' '+url+' FAILED: '+(e&&e.message?e.message:e));
      throw e;
    });
}

function bps(n){if(n>=1048576)return(n/1048576).toFixed(1)+' MB/s';if(n>=1024)return(n/1024).toFixed(1)+' KB/s';return n+' B/s';}
function bytes(n){if(n>=1073741824)return(n/1073741824).toFixed(2)+' GB';if(n>=1048576)return(n/1048576).toFixed(2)+' MB';if(n>=1024)return(n/1024).toFixed(1)+' KB';return n+' B';}
function hms(s){return[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(function(x){return('0'+x).slice(-2);}).join(':');}

function set(id,v){var e=document.getElementById(id);if(e)e.textContent=v;}
function setPill(st){
  var p=document.getElementById('pill');
  if(!p)return;
  p.textContent=st;p.className='pill '+(st==='OK'?'ok':st==='SWP'?'swp':st==='LCK'?'lck':'');
}
function show(id){var e=document.getElementById(id);if(e)e.style.display='block';}
function hide(id){var e=document.getElementById(id);if(e)e.style.display='none';}

function clearLog(){
  var n=document.getElementById('log').children.length;
  ['log','logFull'].forEach(function(id){var e=document.getElementById(id);if(e)e.innerHTML='';});
  updateFillBar();
  console.log('[autolink] button: clear log (cleared '+n+' entries)');
}
// Walk the live log's child nodes (each line
// is a <div>) and join with \n + trailing
// newline so Copy and Save emit unix-line-
// delimited plain text. textContent on the
// parent renders with no line breaks at all
// (block boundaries collapse).
function al_logAsText(){
  var log=document.getElementById('log');
  if(!log)return'';
  var parts=[];
  for(var i=0;i<log.children.length;i++){
    var c=log.children[i];
    if(c.textContent)parts.push(c.textContent);
  }
  return parts.join('\n')+(parts.length?'\n':'');
}
function copyLog(){
  var t=al_logAsText();
  var bytes=t.length;
  // Even with an empty log we still attempt
  // the clipboard write so the button label
  // flips to "Copied" + reverts on the
  // standard path. textContent alone is
  // non-empty from inline-block whitespace;
  // tests pin the label-revert behavior.
  if(navigator.clipboard){
    navigator.clipboard.writeText(t).then(function(){
      var b=document.getElementById('cbtn');
      b.textContent='\u2713 Copied';
      setTimeout(function(){b.textContent='Copy';},1200);
      console.log('[autolink] button: copy log ('+bytes+' bytes copied to clipboard)');
    }).catch(function(e){
      fallbackCopy(t,document.getElementById('cbtn'));
      console.warn('[autolink] copy log: clipboard API failed ('+(e&&e.message?e.message:e)+'), used fallback');
    });
  }else{
    fallbackCopy(t,document.getElementById('cbtn'));
    console.log('[autolink] button: copy log (fallback path, '+bytes+' bytes)');
  }
}

function saveLog(){
  var t=al_logAsText();
  if(!t.length){
    console.warn('[autolink] save log: log is empty, nothing to save');
    return;
  }
  var name=(deviceRole==='Pong'?'pong.txt':(deviceRole==='Ping'?'ping.txt':'autolink.txt'));
  try{
    var blob=new Blob([t],{type:'text/plain;charset=utf-8'});
    var url=URL.createObjectURL(blob);
    var a=document.createElement('a');
    a.href=url;
    a.download=name;
    a.style.display='none';
    document.body.appendChild(a);
    a.click();
    setTimeout(function(){document.body.removeChild(a);URL.revokeObjectURL(url);},200);
    var b=document.getElementById('sbtn');
    b.textContent='\u2713 Saved';
    setTimeout(function(){b.textContent='Save';},1200);
    console.log('[autolink] button: save log ('+t.length+' bytes -> '+name+')');
  }catch(e){
    console.warn('[autolink] save log failed: '+(e&&e.message?e.message:e));
  }
}
function togglePause(){
  logPaused=!logPaused;
  var lbl=logPaused?'\u25b6 Resume':'\u25ae\u25ae Pause';
  ['pbtn','pbtn2'].forEach(function(id){var b=document.getElementById(id);if(b)b.textContent=lbl;});
  console.log('[autolink] button: log scroll '+(logPaused?'paused':'resumed'));
}

async function toggleMsgPause(){
  if(deviceRole!=='Ping'){
    console.log('[autolink] toggleMsgPause ignored — device role is '+deviceRole+' (not Ping)');
    return;
  }
  msgPaused=!msgPaused;
  applyMsgPauseLabel();
  console.log('[autolink] button: message pause -> '+msgPaused+' (sending /pausemsg)');
  try{
    var r=await tfetch('/pausemsg?p='+(msgPaused?'1':'0'),{method:'POST'},5000);
    if(!r.ok){
      console.warn('[autolink] /pausemsg returned '+r.status+' — local UI shows last-known state until /stats reconciles');
    }
  } catch(e){
    console.warn('[autolink] /pausemsg fetch failed: '+(e&&e.message?e.message:e)+' — local UI shows last-known state until /stats reconciles');
  }
}
function applyMsgPauseLabel(){
  var b=document.getElementById('topPbtn');
  if(b){
    if(msgPaused){b.innerHTML='\u25b6 Start';b.className='btn pause on';}
    else{b.innerHTML='\u25ae\u25ae Pause';b.className='btn pause';}
  }
}

// SYNC/ASYNC link-mode toggle. Persisted to NVS on the device;
// the firmware reboots on success. The dashboard reconciles the
// pill from /stats once the device comes back.
async function toggleLinkMode(){
  var cur=(typeof currentLinkMode!=='undefined'&&currentLinkMode)?currentLinkMode:'SYNC';
  var nxt=(cur==='SYNC')?'ASYNC':'SYNC';
  if(!confirm('Switch link mode from '+cur+' to '+nxt+'? The device will reboot.'))return;
  var b=document.getElementById('modeToggleBtn');
  if(b){b.textContent='\u2026';b.disabled=true;}
  console.log('[autolink] button: link mode toggle '+cur+' -> '+nxt+' (sending /mode/toggle)');
  try{
    var r=await tfetch('/mode/toggle',{method:'POST'},5000);
    if(r.ok){
      var body=await r.text();
      console.log('[autolink] /mode/toggle ack: '+body);
      clearLog();lastSeq=0;
      show('alert');
      var tries=0;
      var iv=setInterval(async function(){
        tries++;
        try{
          var rr=await tfetch('/stats',null,5000);
          if(rr.ok){clearInterval(iv);console.log('[autolink] mode toggle: device back online after '+(tries+1)+' s, reloading');location.reload();}
        }catch(_){}
        if(tries>30){clearInterval(iv);console.warn('[autolink] mode toggle: device did not come back online within 30 s');}
      },1000);
    }else{
      if(b){b.textContent='\u2717 Err';setTimeout(function(){b.textContent='\u21c6 Toggle';b.disabled=false;},1500);}
      console.warn('[autolink] /mode/toggle returned '+r.status);
    }
  }catch(e){
    if(b){b.textContent='\u2717 Err';setTimeout(function(){b.textContent='\u21c6 Toggle';b.disabled=false;},1500);}
    console.warn('[autolink] /mode/toggle fetch failed: '+(e&&e.message?e.message:e));
  }
}
function applyLinkModeLabel(m){
  var p=document.getElementById('linkModePill');
  if(p){p.textContent=m;}
  currentLinkMode=m;
}

// Cookie helpers: persist the last delay-ms
// choice across reloads.
function al_cookie_set(name, val, days){
  var d=new Date();
  d.setTime(d.getTime()+(days||365)*24*60*60*1000);
  document.cookie=name+'='+encodeURIComponent(val)+
    ';expires='+d.toUTCString()+';path=/;SameSite=Lax';
}
function al_cookie_get(name){
  var m=document.cookie.match(new RegExp('(?:^|; )'+name+'=([^;]*)'));
  return m?decodeURIComponent(m[1]):null;
}

async function onDelayChange(val){
  var ms=parseInt(val,10);
  if(isNaN(ms)||ms<0)ms=0;
  al_cookie_set('al_delay_ms', String(ms));
  console.log('[autolink] delay widget: txDelayMs='+ms+' (sending /delay, cookie saved)');
  try{
    var r=await tfetch('/delay?ms='+ms,{method:'POST'},5000);
    if(!r.ok){
      console.warn('[autolink] /delay returned '+r.status+' — local UI shows last-known state until /stats reconciles');
    }
  }catch(e){
    console.warn('[autolink] /delay fetch failed: '+(e&&e.message?e.message:e)+' — local UI shows last-known state until /stats reconciles');
  }
}

function bindLvlGroup(name){
  document.querySelectorAll('input[name='+name+']').forEach(function(r){
    r.addEventListener('change',async function(){
      if(!this.checked)return;
      var lv=this.value;
      console.log('[autolink] button: log level change -> lv='+lv);
      try{
        var r2=await tfetch('/level?lv='+encodeURIComponent(lv),{method:'POST'},5000);
        if(r2.ok){
          currentLvl=lv;
          highlightLvl();
          console.log('[autolink] log level set: lv='+lv+' (firmware applied)');
        }else{
          console.warn('[autolink] log level set: firmware rejected lv='+lv+' (http '+(r2.status||'?')+')');
        }
      }catch(e){
        console.warn('[autolink] log level set failed: '+(e&&e.message?e.message:e));
      }
    });
  });
}
bindLvlGroup('lvl');
bindLvlGroup('lvl2');
function highlightLvl(){
  document.querySelectorAll('.lvl-group label').forEach(function(l){
    var inp=l.querySelector('input');
    l.classList.toggle('on',inp&&inp.value===currentLvl);
  });
}

function bindModeGroup(name){
  document.querySelectorAll('input[name='+name+']').forEach(function(r){
    r.addEventListener('change',async function(){
      if(!this.checked)return;
      var m=this.value;
      console.log('[autolink] button: fill mode change -> m='+m);
      try{
        var r2=await tfetch('/mode?m='+encodeURIComponent(m),{method:'POST'},5000);
        if(r2.ok){
          currentMode=m;
          highlightMode();
          console.log('[autolink] fill mode set: m='+m+' (firmware applied)');
        }else{
          console.warn('[autolink] fill mode set: firmware rejected m='+m+' (http '+(r2.status||'?')+', likely Pong side)');
        }
      }catch(e){
        console.warn('[autolink] fill mode set failed: '+(e&&e.message?e.message:e));
      }
    });
  });
}
bindModeGroup('mode');
function highlightMode(){
  document.querySelectorAll('.lvl-group label').forEach(function(l){
    var inp=l.querySelector('input');
    if(inp&&inp.name==='mode')l.classList.toggle('on',inp.value===currentMode);
  });
}

async function poll(){
  if(busy)return;
  busy=true;

  try{
    try{
    var r=await tfetch('/stats',null,5000);
    if(!r.ok)throw 0;
    var d=await r.json();

    set('txbps',bps(d.txBps));
    set('txtot','total '+bytes(d.txTotal));
    set('rxbps',bps(d.rxBps));
    set('rxtot','total '+bytes(d.rxTotal));
    set('discon', d.errTotal);
    var lm=d.lostMsgs||0;
    set('lostmsgs', lm + (lm===1?' lost msg':' lost msgs'));
    var ec=d.errCount||0;
    set('errcnt', ec + (ec===1?' frame error':' frame errors'));
    set('rssi',d.rssi+' dBm');
    set('heap','heap '+bytes(d.freeHeap));
    if(d.state==='OK'){
      set('baud', d.baudRate ? d.baudRate.toLocaleString()+' baud' : '?');
    } else if(d.state==='SWP'){
      set('baud', (d.baudRate ? d.baudRate.toLocaleString() : '?')+' \u21c4 sweeping');
    } else if(d.state==='LCK'){
      set('baud', (d.baudRate ? d.baudRate.toLocaleString() : '?')+' \u21c4 locking');
    } else {
      set('baud', d.baudRate ? d.baudRate.toLocaleString()+' baud' : '\u2014');
    }
    set('uptime','up '+hms(d.uptimeS));
    setPill(d.state);
    if(d.version){
      document.getElementById('ver').textContent='v'+d.version;
      if(!window._autolinkLoggedVer){
        window._autolinkLoggedVer=true;
        console.log('[autolink] device firmware reports v'+d.version);
      }
    }

    var rp=document.getElementById('rolePill');
    if(rp){
      if(d.role&&d.role.length){
        rp.textContent=d.role;
        rp.classList.remove('empty');
      }else{
        rp.textContent='';
        rp.classList.add('empty');
      }
    }

    if(d.role==='Ping'){
      deviceRole='Ping';
      document.body.setAttribute('data-role','ping');
    }else if(d.role==='Pong'){
      deviceRole='Pong';
      document.body.setAttribute('data-role','pong');

      document.querySelectorAll('.ping-only').forEach(function(el){
        el.style.display='none';
      });
    }

    if(d.lvl!==undefined&&d.lvl!==null&&String(d.lvl)!==currentLvl){
      currentLvl=String(d.lvl);
      document.querySelectorAll('input[name=lvl][value="'+currentLvl+'"], input[name=lvl2][value="'+currentLvl+'"]').forEach(function(r){r.checked=true;});
      highlightLvl();
    }

    if(d.mode!==undefined&&d.mode!==null){
      var m=d.mode===1?'rand':'seq';
      if(m!==currentMode){
        currentMode=m;
        var inp=document.querySelector('input[name=mode][value="'+m+'"]');
        if(inp)inp.checked=true;
        highlightMode();
      }
    }

    if(d.linkModeLabel!==undefined&&d.linkModeLabel!==null){
      if(d.linkModeLabel!==currentLinkMode){
        applyLinkModeLabel(d.linkModeLabel);
        console.log('[autolink] /stats linkModeLabel='+d.linkModeLabel+' — reconciled mode pill');
      }
    }

    if(d.msgPaused!==undefined&&d.msgPaused!==null){
      var devPaused=d.msgPaused===1;
      if(devPaused!==msgPaused){
        msgPaused=devPaused;
        applyMsgPauseLabel();
        console.log('[autolink] /stats msgPaused='+devPaused+' — reconciled button label');
      }
    }

    if(d.txDelayMs!==undefined&&d.txDelayMs!==null){
      var sel=document.getElementById('delayMs');
      if(sel){
        var devMs=String(d.txDelayMs);
        // Don't fight the user: if they just clicked the dropdown,
        // /stats will catch up next poll. Only update if it differs
        // and the dropdown isn't currently focused.
        if(devMs!==sel.value&&document.activeElement!==sel){
          sel.value=devMs;
          console.log('[autolink] /stats txDelayMs='+d.txDelayMs+' — synced dropdown (cookie unchanged)');
        }
      }
    }
    fails=0;hide('alert');
    console.log('[autolink] /stats OK state='+d.state+' rxBps='+d.rxBps);
    }catch(e){
      var ec=(e&&e.code)||'';
      var em=(e&&e.message)||String(e);
      console.warn('[autolink] /stats poll failed #'+fails+' code='+ec+' msg='+em);
      if(++fails>=3){
        show('alert');
        if(/^(NETWORKERR|ERR_CONNECTION|ECONNREFUSED|ECONNRESET|ETIMEDOUT)/.test(ec)){
          if(fails>=8){try{location.reload();}catch(_){}}
        }
      }
    }
    try{
    var r2=await tfetch('/logs?since='+lastSeq,null,5000);
    if(!r2.ok)throw new Error('http '+r2.status);
    var d2=await r2.json();
    if(lastSeq===0 && d2.head!==undefined){
      lastSeq=d2.head;
    }else{
      var got=d2.lines?d2.lines.length:0;
      if(got>0)console.log('[autolink] /logs '+got+' new line(s) (since='+lastSeq+')');
      d2.lines.forEach(function(l){appendLog(l.sev,l.seq,l.text);});
    }
    }catch(e){
      console.warn('[autolink] /logs poll failed: '+((e&&e.message)||e));
    }
  }finally{
    busy=false;
  }
}

document.addEventListener('visibilitychange',function(){if(!document.hidden){console.log('[autolink] tab visible — resuming poll');poll();}});
setInterval(poll,1000);
poll().then(function(){
  var _role=document.body.getAttribute('data-role')||'unknown';
  var _state=document.getElementById('pill')?document.getElementById('pill').textContent:'?';
  console.log('[autolink] startup OK — dashboard connected to firmware v)DASH" AUTOLINK_VERSION R"DASH( role='+_role+' state='+_state);
  // Rehydrate delay widget: cookie value wins if set, else
  // firmware's current txDelayMs (from /stats). Cookie is the
  // user-sticky default so a reload restores the last choice.
  var _sel=document.getElementById('delayMs');
  if(_sel){
    var _ck=al_cookie_get('al_delay_ms');
    if(_ck!==null){
      _sel.value=_ck;
      onDelayChange(_ck);
      console.log('[autolink] delay widget: rehydrated from cookie='+_ck);
    } else {
      console.log('[autolink] delay widget: no cookie, using firmware default');
    }
  }
}).catch(function(e){
  console.error('[autolink] startup FAILED: '+(e&&e.message?e.message:e), '— dashboard will retry every 1 s');
});
)DASH" R"DASH(</script>
</body>
</html>)DASH";
} // namespace autolink
