name=AutoLink
version=6.1.67
author=Developer
maintainer=Developer
sentence=Auto-negotiating UART link for ESP32 
category=Communication
url=https://github.com/Systemsplanet/autolink
architectures=esp32
depends=FS, LittleFS, WiFi, Preferences
includes=AutoLink.h,PingPong.h,al/web/AutoLinkWeb.h,al/web/AutoLinkWebCore.h,al/util/Log.h,al/pingpong/PingPongMain.h,al/pingpong/Ping.h,al/pingpong/Pong.h
